baseURL = 'https://mociun.xyz/'
theme = 'hugo-bearcub'
languageCode = 'en-us'
copyright = "Wiktor Mociun (CC BY 4.0)"
defaultContentLanguage = "en"
enableRobotsTXT = true

[languages]
  [languages.en]
    madeWith = "Made with <a href=\"https://github.com/clente/hugo-bearcub\" target=\"_blank\">Bear Cub</a>"
    title = "Wiktor Mociun"

[author]
  name = "Wiktor Mociun"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[params]
  description = "A personal website of a programmer based in Berlin, Germany"
  title = "Wiktor Mociun"
